version: '3'
services:

  fastapi:
    image: "${DOCKER_REGISTRY}/rhi-server"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-python3.9.7
    restart: always
    ports:
      - 45312:80
    volumes:
      - "./:/srv"
