version: '3'
services:

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-python3.9.7
    restart: always
    ports:
      - 8080:80
    volumes:
      - "../:/srv"
