version: '3'
services:

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: fastapi-python3.9.7
    restart: always
    ports:
      - 20080:80
    volumes:
      - "./:/srv"
      - "./var:/storage"
