version: '3'
services:

  fastapi:
    image: 192.168.1.250:32768/rhi-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-python3.9.7
    restart: always
    ports:
      - 20080:80
    volumes:
      - "./:/srv"
