FROM multiarch/alpine:armhf-v3.12

ENV APPDIR /srv
WORKDIR ${APPDIR}

RUN apk update
RUN apk add python3 python3-dev py3-pip sqlite gcc musl-dev libffi-dev openssl-dev bash rust cargo
RUN pip3 install -U pip poetry

ENV TINI_VERSION v0.19.0
ENV TINI_PATH /usr/bin/tini
RUN curl -sL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini > $TINI_PATH && \
    chmod +x $TINI_PATH

ENV DOCKERIZE_VERSION v0.6.1
RUN curl -sL https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz  | tar -C /usr/local/bin -xz

COPY pyproject.toml poetry.lock ${APPDIR}/
RUN poetry config virtualenvs.create false && \
    poetry install -n

COPY ./ ${APPDIR}/

ENTRYPOINT ["tini", "--"]
CMD ["dockerize", "./run.sh"]
